import torch
from torch.func import jacrev

from abc import abstractmethod
from inspect import signature
from typing import Union, Self, override, Callable

from dmol.diff_mfld.util import PartialSpec, DerivedPartialSpec, classproperty, specs_match
from dmol.diff_mfld.mfld import Manifold, Point
from dmol.diff_mfld.bundle.vector_bundle import (
    ScalarBundle,
    VectorBundle,
    TangentBundle,
    CotangentBundle,
    TensorBundle,
)
from dmol.diff_mfld.bundle.tensor import Tensor
from dmol.diff_mfld.connection.connection import Connection
from dmol.diff_mfld.util import split_coords


class Field(metaclass=PartialSpec):
    _tensor: type[Tensor]

    def __class_getitem__(cls, args) -> type[Self]:
        bundle: type[VectorBundle] = args
        if not issubclass(bundle, VectorBundle):
            raise TypeError()

        namespace: dict[str, object] = {"_tensor": Tensor[bundle]}
        if bundle.incomplete:
            namespace.update({"__class_getitem__": cls._spec_incomplete_base})

        return DerivedPartialSpec(f"Field[{bundle.__name__}]", (cls,), namespace)  # pyright: ignore[reportReturnType]

    @staticmethod
    def _spec_incomplete_base(dcls, args):
        underlying_base: type[Manifold] = args
        if not issubclass(underlying_base, Manifold):
            raise TypeError(f"not provided a manifold type {underlying_base.__name__}")

        upd_tensor = dcls._tensor[underlying_base]
        return DerivedPartialSpec(
            f"Field[{upd_tensor.bundle.__name__}]",
            (dcls,),
            {"_tensor": upd_tensor},
        )  # pyright: ignore[reportReturnType]

    def __init__(self):
        if type(self) == Field:
            raise TypeError("fields cannot be instantiated without being subclassed")

    def __call__(self, p: Union[Point, torch.Tensor]):
        # TODO: add options to the library to rigidly enforce properly typed point input
        p = Point[self._tensor.bundle.base](p)  # ensures that the point is compatible
        return self._tensor(self._eval(p.p))

    def partials(self, p: Union[Point, torch.Tensor]) -> torch.Tensor:
        p = Point[self._tensor._bundle.base](p)
        partials = self._eval_partials(p.p)

        expected_shape = torch.Size((*self._tensor.shape, self._tensor.bundle.base.dim))
        if partials.shape != expected_shape:
            raise ValueError(f"partials generated by {self.__class__.__name__} is unexpected shape")

        return partials

    @classproperty
    def tensor(cls):
        return cls._tensor

    @abstractmethod
    def _eval(self, p: torch.Tensor) -> torch.Tensor:
        pass

    @abstractmethod
    def _eval_partials(self, p: torch.Tensor) -> torch.Tensor:
        # NOTE: default behavior assumes that the eval mapping is continuous, must override if discrete or approximate
        partials = jacrev(self._eval)(p)
        return partials


class LambdaField(Field):
    def __init__(self, field_fn: Callable[[torch.Tensor | tuple[torch.Tensor, ...]], torch.Tensor]):
        super().__init__()

        n = self.tensor.bundle.base.dim
        num_args = len(signature(field_fn).parameters)

        if num_args > 1:
            if num_args != n:
                raise ValueError(f"provided function accepts {num_args} but manifold has {n} dimensions")
            self._has_coord_fn = True
        else:
            self._has_coord_fn = False
        self._field_fn = field_fn

    @override
    def _eval(self, p: torch.Tensor):
        if self._has_coord_fn:
            coords = split_coords(p)
            components = self._field_fn(*coords)
        else:
            components = self._field_fn(p)
        return components


# class DiffField(Field):
#     _covar_bundle: type[VectorBundle]


# # specially-named fields for better clarity


# class VectorField(DiffField[Tensor[TangentBundle]]):
#     _covar_bundle = TensorBundle[1, 1]


# class CovectorField(DiffField[Tensor[CotangentBundle]]):
#     _field_bundle = Field[Tensor[TensorBundle[0, 2]]]


# class ScalarField(DiffField[Tensor[ScalarBundle]]):
#     _field_bundle_type = CotangentBundle
