import torch
from torch.func import jacrev

from abc import abstractmethod
from typing import Union, Self

from dmol.diff_mfld.util import PartialSpec, DerivedPartialSpec, classproperty, specs_match
from dmol.diff_mfld.mfld import Manifold, Point
from dmol.diff_mfld.bundle.vector_bundle import VectorBundle, _bundles_compatible
from dmol.diff_mfld.bundle.tensor import Tensor


class Field(metaclass=PartialSpec):
    _tensor: type[Tensor]

    def __class_getitem__(cls, args) -> type[Self]:
        ty: type[VectorBundle] | type[Tensor] = args

        if issubclass(ty, VectorBundle):
            tensor_ty = Tensor[ty]
        elif issubclass(ty, Tensor):
            tensor_ty = ty
        else:
            raise TypeError()

        namespace: dict[str, object] = {"_tensor": tensor_ty}
        if tensor_ty.incomplete:
            namespace.update({"__class_getitem__": cls._spec_incomplete_base})

        return DerivedPartialSpec(
            f"Field[{tensor_ty.__name__}]", (cls,), namespace
        )  # pyright: ignore[reportReturnType]

    @staticmethod
    def _spec_incomplete_base(dcls, args):
        underlying_base: type[Manifold] = args
        if not issubclass(underlying_base, Manifold):
            raise TypeError(f"not provided a manifold type {underlying_base.__name__}")

        upd_tensor = dcls._tensor[underlying_base]
        return DerivedPartialSpec(
            f"Field[{upd_tensor.bundle.__name__}]",
            (dcls,),
            {"_tensor": upd_tensor},
        )  # pyright: ignore[reportReturnType]

    def __init__(self):
        if type(self) == Field:
            raise TypeError("fields cannot be instantiated without being subclassed")

    def __call__(self, p: Union[Point, torch.Tensor]) -> Tensor:
        # TODO: add options to the library to rigidly enforce properly typed point input
        p = Point[self._tensor.bundle.base](p)  # ensures that the point is compatible
        return self._tensor(self._eval(p.p))

    def partials(self, p: Union[Point, torch.Tensor]) -> torch.Tensor:
        p = Point[self._tensor._bundle.base](p)
        partials = self._eval_partials(p.p)

        expected_shape = torch.Size((*self._tensor.shape, self._tensor.bundle.base.dim))
        if partials.shape != expected_shape:
            raise ValueError(f"partials generated by {self.__class__.__name__} is unexpected shape")

        return partials

    @classproperty
    def tensor(self) -> type[Tensor]:
        return self._tensor

    @classproperty
    def bundle(cls) -> type[VectorBundle]:
        return cls._tensor.bundle

    @classmethod
    def validate_field(cls, f: Field):
        if cls.incomplete:
            raise TypeError("field type must be fully specialized to validate instances")
        elif not specs_match(cls, type(f)):
            raise ValueError(f"instance with tensor {f.tensor} must match tensor {cls.tensor}")

    @classmethod
    def compatible_field(cls, f: Field) -> bool:
        if cls.incomplete:
            raise TypeError("field type must be fully specialized to check compatibility with instances")
        return _bundles_compatible(cls.bundle, f.bundle)

    @abstractmethod
    def _eval(self, p: torch.Tensor) -> torch.Tensor:
        raise NotImplementedError()

    @abstractmethod
    def _eval_partials(self, p: torch.Tensor) -> torch.Tensor:
        # NOTE: default behavior assumes that the eval mapping is continuous, must override if discrete or approximate
        partials = jacrev(self._eval)(p)
        return partials

    # to be overridden

    def __add__(self, other):
        raise NotImplementedError()

    def __sub__(self, other):
        raise NotImplementedError()

    def __mul__(self, other):
        raise NotImplementedError()

    def __rmul__(self, other):
        raise NotImplementedError()
