import torch
from torch.func import jacrev

from abc import abstractmethod
from inspect import signature
from typing import Union, Self, override, Callable, Sequence

from dmol.diff_mfld.util import PartialSpec, DerivedPartialSpec, classproperty, specs_match
from dmol.diff_mfld.mfld import Manifold, Point
from dmol.diff_mfld.bundle.vector_bundle import (
    ScalarBundle,
    VectorBundle,
    TangentBundle,
    CotangentBundle,
)
from dmol.diff_mfld.bundle.tensor import Tensor, _get_compatible_bundle, _bundles_compatible
from dmol.diff_mfld.util import split_coords


class Field(metaclass=PartialSpec):
    _tensor: type[Tensor]

    def __class_getitem__(cls, args) -> type[Self]:
        ty: type[VectorBundle] | type[Tensor] = args

        if issubclass(ty, VectorBundle):
            tensor_ty = Tensor[ty]
        elif issubclass(ty, Tensor):
            tensor_ty = ty
        else:
            raise TypeError()

        namespace: dict[str, object] = {"_tensor": tensor_ty}
        if tensor_ty.incomplete:
            namespace.update({"__class_getitem__": cls._spec_incomplete_base})

        return DerivedPartialSpec(
            f"Field[{tensor_ty.__name__}]", (cls,), namespace
        )  # pyright: ignore[reportReturnType]

    @staticmethod
    def _spec_incomplete_base(dcls, args):
        underlying_base: type[Manifold] = args
        if not issubclass(underlying_base, Manifold):
            raise TypeError(f"not provided a manifold type {underlying_base.__name__}")

        upd_tensor = dcls._tensor[underlying_base]
        return DerivedPartialSpec(
            f"Field[{upd_tensor.bundle.__name__}]",
            (dcls,),
            {"_tensor": upd_tensor},
        )  # pyright: ignore[reportReturnType]

    def __init__(self):
        if type(self) == Field:
            raise TypeError("fields cannot be instantiated without being subclassed")

    def __call__(self, p: Union[Point, torch.Tensor]) -> Tensor:
        # TODO: add options to the library to rigidly enforce properly typed point input
        p = Point[self._tensor.bundle.base](p)  # ensures that the point is compatible
        return self._tensor(self._eval(p.p))

    def partials(self, p: Union[Point, torch.Tensor]) -> torch.Tensor:
        p = Point[self._tensor._bundle.base](p)
        partials = self._eval_partials(p.p)

        expected_shape = torch.Size((*self._tensor.shape, self._tensor.bundle.base.dim))
        if partials.shape != expected_shape:
            raise ValueError(f"partials generated by {self.__class__.__name__} is unexpected shape")

        return partials

    @classproperty
    def tensor(cls) -> type[Tensor]:
        return cls._tensor

    @classproperty
    def bundle(cls) -> type[VectorBundle]:
        return cls._tensor.bundle

    @abstractmethod
    def _eval(self, p: torch.Tensor) -> torch.Tensor:
        pass

    @abstractmethod
    def _eval_partials(self, p: torch.Tensor) -> torch.Tensor:
        # NOTE: default behavior assumes that the eval mapping is continuous, must override if discrete or approximate
        partials = jacrev(self._eval)(p)
        return partials

    @classmethod
    def validate_field(cls, f: Field):
        if cls.incomplete:
            raise TypeError("field type must be fully specialized to validate instances")
        elif not specs_match(cls, type(f)):
            raise ValueError(f"instance with tensor {f.tensor} must match tensor {cls.tensor}")

    def __add__(self, other):
        if isinstance(other, Field):
            result_bundle = _get_compatible_bundle(self.bundle, other.bundle)
            return _AddField[result_bundle](self, other)
        raise NotImplemented()

    def __sub__(self, other):
        if isinstance(other, Field):
            result_bundle = _get_compatible_bundle(self.bundle, other.bundle)
            return _SubField[result_bundle](self, other)
        raise NotImplemented()

    def __mul__(self, other):
        lhs, rhs = self, other  # for clarity
        return _shared_field_mul(lhs, rhs)

    def __rmul__(self, other):
        lhs, rhs = other, self
        return _shared_field_mul(lhs, rhs)


def fields_compatible(f1: Field, f2: type[Field]) -> bool:
    return _bundles_compatible(f1.bundle, f2.bundle)


def _shared_field_mul(lhs: Field | float, rhs: Field | float):
    if isinstance(lhs, Field) and isinstance(rhs, Field):
        scalar_bundle = ScalarBundle[lhs.bundle.base]
        if _bundles_compatible(lhs.bundle, scalar_bundle) and _bundles_compatible(rhs.bundle, scalar_bundle):
            return _MulField[scalar_bundle](lhs, rhs)
        elif _bundles_compatible(lhs.bundle, scalar_bundle):
            return _MulField[rhs.bundle](lhs, rhs)
        elif _bundles_compatible(rhs.bundle, scalar_bundle):
            return _MulField[lhs.bundle](lhs, rhs)
        else:
            raise ValueError("at least one field must be compatible to a ScalarField")
    elif isinstance(lhs, Field):
        return _MulField[lhs.bundle](lhs, rhs)
    elif isinstance(rhs, Field):
        return _MulField[rhs.bundle](lhs, rhs)
    raise NotImplemented()  # not reachable


# following are simple wrappers with no checks for internal use only (note these are implemented as separate fields to
# allow custom behavior when evaluating the covariant derivative)


class _AddField(Field):
    def __init__(self, field: Field, other: Field):
        super().__init__()
        self._field = field
        self._other = other

    @override
    def _eval(self, p: torch.Tensor) -> torch.Tensor:
        return self._field._eval(p) + self._other._eval(p)

    @override
    def _eval_partials(self, p: torch.Tensor) -> torch.Tensor:
        return self._field._eval_partials(p) + self._other._eval_partials(p)

    def __repr__(self) -> str:
        return f"_AddField[{self._field}, {self._other}]"


class _SubField(Field):
    def __init__(self, field: Field, other: Field):
        super().__init__()
        self._field = field
        self._other = other

    @override
    def _eval(self, p: torch.Tensor) -> torch.Tensor:
        return self._field._eval(p) - self._other._eval(p)

    @override
    def _eval_partials(self, p: torch.Tensor) -> torch.Tensor:
        return self._field._eval_partials(p) - self._other._eval_partials(p)

    def __repr__(self) -> str:
        return f"_SubField[{self._field}, {self._other}]"


class _MulField(Field):
    def __init__(self, lhs: Field | float, rhs: Field | float):
        super().__init__()
        self._lhs = lhs
        self._rhs = rhs

        self._is_lhs_field = not type(lhs) is float
        self._is_rhs_field = not type(rhs) is float

    @override
    def _eval(self, p: torch.Tensor) -> torch.Tensor:
        if self._is_lhs_field and self._is_rhs_field:
            return self._lhs._eval(p) * self._rhs._eval(p)  # type: ignore
        elif self._is_lhs_field:
            return self._lhs._eval(p) * self._rhs  # type: ignore
        elif self._is_rhs_field:
            return self._lhs * self._rhs._eval(p)  # type: ignore
        raise RuntimeError()  # not reachable

    @override
    def _eval_partials(self, p: torch.Tensor) -> torch.Tensor:
        if self._is_lhs_field and self._is_rhs_field:
            result = torch.outer(self._lhs._eval_partials(p), self._rhs._eval(p))  # type: ignore
            result += torch.outer(self._lhs._eval(p), self._rhs._eval_partials(p))  # type: ignore
            return result
        elif self._is_lhs_field:
            return self._lhs._eval_partials(p) * self._rhs  # type: ignore
        elif self._is_rhs_field:
            return self._lhs * self._rhs._eval_partials(p)  # type: ignore
        raise RuntimeError()  # not reachabl

    def __repr__(self) -> str:
        return f"_MulField[{self._lhs}, {self._rhs}]"


def coord_repr(
    repr: torch.Tensor | float | Sequence[torch.Tensor | float] | Sequence[Sequence[torch.Tensor | float]],
) -> torch.Tensor:
    # scalar-valued
    if type(repr) is torch.Tensor:
        return repr
    elif type(repr) is float:
        return torch.tensor(repr)
    # vector-valued
    elif type(repr[0]) is torch.Tensor or type(repr[0]) is float:  # type: ignore
        vec_repr: Collection[torch.Tensor | float, ...] = repr  # type: ignore
        n = len(vec_repr)

        vec = torch.zeros((n,))
        for i in range(n):
            vec[i] = vec_repr[i]
        return vec
    # matrix-valued
    else:
        mat_repr: Collection[Collection[torch.Tensor | float, ...], ...] = repr  # type: ignore
        n = len(mat_repr)
        m = len(mat_repr[0])

        mat = torch.zeros((n, m))
        for i in range(n):
            for j in range(m):
                mat[i, j] = mat_repr[i][j]
        return mat


def check_field_expr_callable_for_gradient(
    fn: Callable[[*tuple[torch.Tensor, ...]], torch.Tensor],
    coord_dim: int,
    single_arg=False,
    num_samples=20,
    coord_mean=2.0,
    coord_std=5.0,
):
    p_dist = torch.distributions.MultivariateNormal(
        coord_mean * torch.ones((coord_dim,)), coord_std**2 * torch.eye(coord_dim)
    )

    fn_single_arg = fn if single_arg else lambda p: fn(*split_coords(p))
    fn_grad = jacrev(fn_single_arg)

    # samples the initial point
    p_initial = p_dist.sample()
    initial_val = fn_single_arg(p_initial)

    for _ in range(num_samples):
        p_sample = p_dist.sample()
        val = fn_single_arg(p_sample)
        grad = fn_grad(p_sample)

        # if the value has changed we expect the gradient to also be nonzero
        if not torch.allclose(initial_val, val):
            if torch.allclose(grad, torch.zeros_like(grad)):
                raise ValueError(
                    "zero gradient detected thereby suggesting probable gradient loss in field expression callable"
                )

        # evaluates between a number of randomly sampled points
        initial_val = val


class LambdaField(Field):
    def __init__(self, field_fn: Callable[[torch.Tensor | tuple[torch.Tensor, ...]], torch.Tensor]):
        super().__init__()

        n = self.tensor.bundle.base.dim
        num_args = len(signature(field_fn).parameters)

        sample_p = torch.zeros((n,))

        if num_args > 1:
            if num_args != n:
                raise ValueError(f"provided function accepts {num_args} but manifold has {n} dimensions")
            self._has_coord_fn = True
            sample_components = field_fn(*split_coords(sample_p))
        else:
            self._has_coord_fn = False
            sample_components = field_fn(sample_p)

        if sample_components.shape != self.tensor.shape:
            raise ValueError()

        self._field_fn = field_fn

    @override
    def _eval(self, p: torch.Tensor):
        if self._has_coord_fn:
            components = self._field_fn(*split_coords(p))
        else:
            components = self._field_fn(p)
        return components


class ScalarField(Field[ScalarBundle]):
    pass


class VectorField(Field[TangentBundle]):
    pass


class CovectorField(Field[CotangentBundle]):
    pass
