import torch
from torch.func import jacrev

from abc import abstractmethod
from typing import Union, Self

from dmol.diff_mfld.util import PartialSpec, classproperty, specs_match
from dmol.diff_mfld.mfld import Manifold, Point
from dmol.diff_mfld.geometry.vector_bundle import VectorBundle
from dmol.diff_mfld.geometry.tensor import Tensor


class Field(metaclass=PartialSpec):
    _tensor: type[Tensor]

    def __class_getitem__(cls, args):
        tensor: type[Tensor] = args
        if not issubclass(tensor, Tensor):
            raise TypeError(f"not provided a tensor type {tensor.__name__}")

        print(f"tensor type: {tensor}")
        namespace = {"_tensor": tensor}
        if tensor.incomplete:
            namespace.update(
                {"__class_getitem__": Field._partial_spec_mfld_pass_to_base}
            )

        return PartialSpec(
            f"Field[{tensor.__name__}]", (cls,), namespace, creating_derived=True
        )

    def _partial_spec_mfld_pass_to_base(cls, args):
        underlying_base: type[Manifold] = args
        if not issubclass(underlying_base, Manifold):
            raise TypeError(f"not provided a manifold type {underlying_base.__name__}")

        print(f"before update tensor: {cls._tensor}")
        upd_tensor = cls._tensor[underlying_base]
        print(f"upd_tensor: {upd_tensor}")
        return PartialSpec(
            f"Field[{upd_tensor.__name__}]",
            (cls,),
            {"_tensor": upd_tensor},
            creating_derived=True,
            top_level_type=cls._top_level_type,
        )

    def __init__(self):
        if type(self) == Field:
            raise TypeError("fields cannot be instantiated without being subclassed")

    def __call__(self, p: Union[Point[Self._tensor._bundle.base], torch.Tensor]):
        # TODO: add options to the library to rigidly enforce properly typed point input
        p = Point[self._tensor.bundle.base](p)  # ensures that the point is compatible
        tensor = self._tensor(self.eval(p.p))

        print(f"type tensor: {type(tensor)}")
        print(f"_tensor: {self._tensor}")

        if type(tensor) is not self._tensor:
            raise ValueError(
                f"tensor generated by {self.__class__.__name__} is incorrect type"
            )
        return tensor

    def partials(
        self, p: Union[Point[Self._bundle.base], torch.Tensor]
    ) -> torch.Tensor:
        p = Point[self._tensor._bundle.base](p)
        partials = self.eval_partials(p.p)

        expected_shape = torch.Size((*self._tensor.shape, self._tensor.bundle.base.dim))

        print(f"partials shape: {partials.shape}")
        print(f"expected shape: {expected_shape}")

        print(partials.shape == expected_shape)

        if partials.shape != expected_shape:
            raise ValueError(
                f"partials generated by {self.__class__.__name__} is unexpected shape"
            )

        return partials

    @classproperty
    def tensor(cls):
        return cls._tensor

    @abstractmethod
    def eval(self, p: torch.Tensor) -> Self._tensor:
        pass

    @abstractmethod
    def eval_partials(self, p: torch.Tensor) -> torch.Tensor:
        # NOTE: default behavior assumes that the eval mapping is continuous, must override if discrete or approximate
        partials = jacrev(self.eval)(p)
        return partials


print()
print()

print(Field.__annotations__)
print(Field.__dict__)

print()
