import torch

from torch.func import jacrev
from abc import abstractmethod

from dataclasses import dataclass
from typing import TYPE_CHECKING

from dmol.diff_mfld.field import Field
from dmol.diff_mfld.field.field_types import VectorField
from dmol.diff_mfld.mfld import Manifold, Point
from dmol.diff_mfld.util import PartialSpec, DerivedPartialSpec, classproperty
from dmol.diff_mfld.bundle.vector_bundle import (
    VectorBundle,
    TensorProductBundle,
)

if TYPE_CHECKING:
    from dmol.diff_mfld.connection.covar_diff import FieldCustomCovar


# class ExpMapMethod:
#     pass


# class LogMapMethod:
#     pass


# class ParallelTranspVecMethod:
#     pass


@dataclass
class ConnectionMethodConfig:
    pass


class Connection(metaclass=PartialSpec):
    _bundle: type[VectorBundle]
    _coeffs_shape: tuple[int, ...]

    def __class_getitem__(cls, args):
        bundle: type[VectorBundle] = args

        # NOTE: for now we will disallow defining connections on tensor product bundles for simplicity as there is no
        # current use case or need given we just need to parallel transport simplisitc quantities

        if issubclass(bundle, TensorProductBundle):
            raise NotImplemented("tensor products bundles are not currently supported by connections")

        n = bundle.base.dim if not bundle.incomplete else None
        r = bundle.rank

        coeffs_shape = (r, r, n)

        namespace = {"_bundle": bundle, "_coeffs_shape": coeffs_shape}
        if bundle.incomplete:
            namespace.update({"__class_getitem__": cls._spec_incomplete_base})

        return DerivedPartialSpec(
            f"Connection[{bundle.__name__}]",
            (cls,),
            namespace,
        )

    @staticmethod
    def _spec_incomplete_base(dcls, args):
        underlying_base: type[Manifold] = args
        upd_bundle = dcls._bundle[underlying_base]

        n = upd_bundle.base.dim
        r = upd_bundle.rank
        coeffs_shape = (r, r, n)

        return DerivedPartialSpec(
            f"Connection[{upd_bundle.__name__}]",
            (dcls,),
            {"_bundle": upd_bundle, "_coeffs_shape": coeffs_shape},
        )

    def __init__(self):
        if type(self) == Connection:
            raise TypeError("connectinos cannot be instantiated without being subclassed")
        self._cfg = ConnectionMethodConfig()  # defaults

    @classproperty
    def bundle(cls):
        return cls._bundle

    @property
    def cfg(self):
        return self._cfg

    def coeffs(self, p: Point | torch.Tensor) -> torch.Tensor:
        p = Point[self._bundle.base](p)  # ensures that the point is compatible
        coeffs = self._eval(p.p)
        if coeffs.shape != self._coeffs_shape:
            raise ValueError(f"connection coefficients generated by {self.__class__.__name__} is incorrect shape")
        return coeffs

    def partials(self, p: Point | torch.Tensor, order: int = 1) -> torch.Tensor:
        p = Point[self._bundle.base](p)
        partials = self._eval_partials(p.p, order)

        n = self._bundle.base.dim
        r = self._bundle.rank

        expected_shape = torch.Size([r, r, n, *([n] * order)])

        if partials.shape != expected_shape:
            raise ValueError(f"partials generated by {self.__class__.__name__} is unexpected shape")

        return partials

    @abstractmethod
    def _eval(self, p: torch.Tensor) -> torch.Tensor:
        # NOTE: default behavior assumes that the eval mapping is continuous, must override if discrete or approximate
        pass

    @abstractmethod
    def _eval_partials(self, p: torch.Tensor, order: int) -> torch.Tensor:
        # NOTE: default behavior assumes that the eval mapping is continuous, must override if discrete or approximate

        partials_fn = jacrev(self._eval)
        for _ in range(1, order):
            partials_fn = jacrev(partials_fn)

        partials = partials_fn(p)
        return partials

    def covar(self, field: Field | FieldCustomCovar, vf: VectorField) -> Field:
        raise NotImplementedError()  # implemented elsewhere

    def total_covar(self, field: Field | FieldCustomCovar) -> Field:
        raise NotImplementedError()  # implemented elsewhere

    @abstractmethod
    def _covar(self, field: Field, vf: VectorField) -> Field:
        raise NotImplementedError("covariant derivatives currently only supported for tangent bundle connections")

    @abstractmethod
    def _total_covar(self, field: Field) -> Field:
        raise NotImplementedError("total covariant derivatives currently only supported for tangent bundle connections")
