import torch

from torch.func import jacrev
from abc import abstractmethod

from dataclasses import dataclass
from typing import Tuple, Union, Callable

from dmol.diff_mfld.mfld import Manifold, Point
from dmol.diff_mfld.util import PartialSpec, DerivedPartialSpec, classproperty
from dmol.diff_mfld.bundle.vector_bundle import TangentBundle, ScalarBundle, CotangentBundle, TensorBundle
from dmol.diff_mfld.bundle.tensor import Tensor, Vec, _bundles_compatible
from dmol.diff_mfld.bundle.field import Field, VectorField
from dmol.diff_mfld.bundle.vector_bundle import (
    VectorBundle,
    TensorProductBundle,
    TangentBundle,
)


class BundleCurve(metaclass=PartialSpec):
    _bundle: type[VectorBundle]

    def __class_getitem__(cls, args):
        bundle: type[VectorBundle] = args

        namespace = {"_bundle": bundle}
        if bundle.incomplete:
            namespace.update({"__class_getitem__": cls._spec_incomplete_base})

        return DerivedPartialSpec(
            f"BundleCurve[{bundle.__name__}]",
            (BundleCurve,),
            namespace,
        )

    @classmethod
    def _spec_incomplete_base(cls, args):
        underlying_manifold: type[Manifold] = args

        upd_bundle = cls._bundle[underlying_manifold]
        namespace: dict[str, object] = {"_bundle": upd_bundle}

        if upd_bundle.incomplete:
            namespace.update({"__class_getitem__": cls._spec_incomplete_base})

        return DerivedPartialSpec(
            f"BundleCurve[{upd_bundle.__name__}]",
            (BundleCurve,),
            namespace,
        )

    def __init__(self, t: torch.Tensor, coords: torch.Tensor, derivs: Tuple[torch.Tensor, ...]):
        self._t = t
        self._coords = coords
        self._derivs = derivs

    @property
    def t(self):
        return self._t

    @property
    def coords(self):
        return self._coords

    @property
    def derivs(self):
        return self._derivs


class ExpMapMethod:
    pass


class LogMapMethod:
    pass


class ParallelTranspVecMethod:
    pass


@dataclass
class ConnectionMethodConfig:
    pass


class Connection(metaclass=PartialSpec):
    _bundle: type[VectorBundle]
    _coeffs_shape: Tuple[int, ...]

    def __class_getitem__(cls, args):
        bundle: type[VectorBundle] = args

        # NOTE: for now we will disallow defining connections on tensor product bundles for simplicity as there is no
        # current use case or need given we just need to parallel transport simplisitc quantities

        if issubclass(bundle, TensorProductBundle):
            raise NotImplemented("tensor products bundles are not currently supported by connections")

        n = bundle.base.dim if not bundle.incomplete else None
        r = bundle.rank

        coeffs_shape = (r, r, n)

        namespace = {"_bundle": bundle, "_coeffs_shape": coeffs_shape}
        if bundle.incomplete:
            namespace.update({"__class_getitem__": cls._spec_incomplete_base})

        return DerivedPartialSpec(
            f"Connection[{bundle.__name__}]",
            (cls,),
            namespace,
        )

    @staticmethod
    def _spec_incomplete_base(dcls, args):
        underlying_base: type[Manifold] = args
        upd_bundle = dcls._bundle[underlying_base]

        n = upd_bundle.base.dim
        r = upd_bundle.rank
        coeffs_shape = (r, r, n)

        return DerivedPartialSpec(
            f"Connection[{upd_bundle.__name__}]",
            (dcls,),
            {"_bundle": upd_bundle, "_coeffs_shape": coeffs_shape},
        )

    def __init__(self):
        if type(self) == Connection:
            raise TypeError("connectinos cannot be instantiated without being subclassed")
        self._cfg = ConnectionMethodConfig()  # defaults

    @classproperty
    def bundle(cls):
        return cls._bundle

    @property
    def cfg(self):
        return self._cfg

    def coeffs(self, p: Union[Point, torch.Tensor]) -> torch.Tensor:
        p = Point[self._bundle.base](p)  # ensures that the point is compatible
        coeffs = self._eval(p.p)
        if coeffs.shape != self._coeffs_shape:
            raise ValueError(f"connection coefficients generated by {self.__class__.__name__} is incorrect shape")
        return coeffs

    def partials(self, p: Union[Point, torch.Tensor], order: int = 1) -> torch.Tensor:
        p = Point[self._bundle.base](p)
        partials = self._eval_partials(p.p, order)

        n = self._bundle.base.dim
        r = self._bundle.rank
        expected_shape = torch.Size([r, r, n, n])

        if partials.shape != expected_shape:
            raise ValueError(f"partials generated by {self.__class__.__name__} is unexpected shape")

        return partials

    @abstractmethod
    def _eval(self, p: torch.Tensor) -> torch.Tensor:
        # NOTE: default behavior assumes that the eval mapping is continuous, must override if discrete or approximate
        pass

    @abstractmethod
    def _eval_partials(self, p: torch.Tensor, order: int) -> torch.Tensor:
        # NOTE: default behavior assumes that the eval mapping is continuous, must override if discrete or approximate

        partials_fn = jacrev(lambda q: self._eval(q))
        for _ in range(1, order):
            partials_fn = jacrev(partials_fn)

        partials = partials_fn(p)
        return partials

    def covar(self, field: Field | FieldCustomCovar, vf: VectorField) -> Field:
        if isinstance(field, FieldCustomCovar):
            return field.covar(vf, self)
        return self._covar(field, vf)

    def total_covar(self, field: Field | FieldCustomCovar) -> Field:
        if isinstance(field, FieldCustomCovar):
            return field.total_covar(self)
        return self._total_covar(field)

    @abstractmethod
    def _covar(self, field: Field, vf: VectorField) -> Field:
        raise NotImplementedError("covariant derivatives currently only supported for tangent bundle connections")

    @abstractmethod
    def _total_covar(self, field: Field) -> Field:
        raise NotImplementedError("total covariant derivatives currently only supported for tangent bundle connections")


class FieldCustomCovar(Field):
    @abstractmethod
    def covar(self, vf: VectorField, conn: Connection) -> Field:
        raise NotImplementedError()

    @abstractmethod
    def total_covar(self, conn: Connection) -> Field:
        raise NotImplementedError()


class _TotalCovarDerivField(Field):
    def __init__(
        self,
        field: Field,
        conn: TangentConnection,
        eval_fn: Callable[[torch.Tensor, Field, TangentConnection], torch.Tensor],
    ):
        super().__init__()
        self._field = field
        self._conn = conn
        self._eval_fn = eval_fn

    @staticmethod
    def scalar_eval(p: torch.Tensor, field: Field, conn: Connection) -> torch.Tensor:
        return field._eval_partials(p)

    @staticmethod
    def cotangent_eval(p: torch.Tensor, field: Field, conn: Connection) -> torch.Tensor:
        return field._eval_partials(p) - torch.einsum("k,kji->ij", field._eval(p), conn.coeffs(p))

    def _eval(self, p: torch.Tensor) -> torch.Tensor:
        return self._eval_fn(p, self._field, self._conn)


class TangentConnection(Connection[TangentBundle]):
    def _covar(self, field: Field, vf: VectorField) -> Field:
        # TODO: add operations on tensors
        raise NotImplementedError()

    def _total_covar(self, field: Field) -> Field:
        # TODO: implement the total covariant derivative for all tensor fields
        if _bundles_compatible(field.bundle, ScalarBundle[field.bundle.base]):
            return _TotalCovarDerivField[CotangentBundle[field.bundle.base]](
                field, self, _TotalCovarDerivField.scalar_eval
            )
        elif _bundles_compatible(field.bundle, CotangentBundle[field.bundle.base]):
            return _TotalCovarDerivField[TensorBundle[0, 2][field.bundle.base]](
                field, self, _TotalCovarDerivField.cotangent_eval
            )
        raise TypeError(
            "total covariant derivative of types other than scalar or cotangent fields are currently not supported"
        )

    @abstractmethod
    def exp(self, p: Point | torch.Tensor, v: Vec, method: ExpMapMethod | None = None) -> Tuple[Point, BundleCurve]:
        Point[self.bundle.base].validate_point(p)
        Tensor[self.bundle].validate_tensor(v)

    @abstractmethod
    def log(
        self,
        p: Point | torch.Tensor,
        q: Point | torch.Tensor,
        method: LogMapMethod | None = None,
    ) -> Tuple[Vec, BundleCurve]:
        Point[self.bundle.base].validate_point(p)
        Point[self.bundle.base].validate_point(q)

    @abstractmethod
    def pt_vec(self, v: Vec, curve: BundleCurve, method: ParallelTranspVecMethod | None = None) -> Vec:
        Tensor[self.bundle].validate_tensor(v)
