import torch

from torch.func import jacrev
from abc import ABC, abstractmethod

from dataclasses import dataclass
from typing import Tuple, Union, Self, Optional, Protocol

from dmol.diff_mfld.mfld import Manifold, Point
from dmol.diff_mfld.util import PartialSpec, classproperty
from dmol.diff_mfld.bundle.tensor import Tensor, Vec

# from dmol.diff_mfld.geometry.field import Field, VectorField
from dmol.diff_mfld.bundle.vector_bundle import VectorBundle, TensorProductBundle


class BundleCurve:
    _bundle: type[VectorBundle]

    def __class_getitem__(cls, args):
        bundle: type[VectorBundle] = args

        namespace = {"_bundle": bundle}
        if bundle.incomplete:
            namespace.update(
                {"__class_getitem__": BundleCurve._partial_spec_mfld_pass_to_base}
            )

        return PartialSpec(
            f"BundleCurve[{bundle.__name__}]",
            (BundleCurve,),
            namespace,
            creating_derived=True,
        )

    def _partial_spec_mfld_pass_to_base(cls, args):
        underlying_manifold: type[Manifold] = args

        upd_bundle = cls._bundle[underlying_manifold]
        namespace = {"_bundle": upd_bundle}

        if upd_bundle.incomplete:
            namespace.update(
                {"__class_getitem__": BundleCurve._partial_spec_mfld_pass_to_base}
            )

        return PartialSpec(
            f"BundleCurve[{upd_bundle.__name__}]",
            (BundleCurve,),
            namespace,
            creating_derived=True,
            top_level_type=cls._top_level_type,
        )

    def __init__(
        self, t: torch.Tensor, coords: torch.Tensor, derivs: Tuple[torch.Tensor, ...]
    ):
        self._t = t
        self._coords = coords
        self._derivs = derivs

    @property
    def t(self):
        return self._t

    @property
    def coords(self):
        return self._coords

    @property
    def derivs(self):
        return self._derivs


class ExpMapMethod:
    pass


class LogMapMethod:
    pass


class ParallelTranspVecMethod:
    pass


@dataclass
class ConnectionMethodConfig:
    pass


class Connection(metaclass=PartialSpec):
    _bundle: type[VectorBundle]
    _coeffs_shape: Tuple[int, ...]

    def __class_getitem__(cls, args):
        bundle: type[VectorBundle] = args

        # NOTE: for now we will disallow defining connections on tensor product bundles for simplicity as there is no
        # current use case or need given we just need to parallel transport simplisitc quantities

        if issubclass(bundle, TensorProductBundle):
            raise NotImplemented(
                "tensor products bundles are not currently supported by connections"
            )

        n = bundle.base.dim if not bundle.incomplete else None
        r = bundle.rank

        coeffs_shape = (r, r, n)

        namespace = {"_bundle": bundle, "_coeffs_shape": coeffs_shape}
        if bundle.incomplete:
            namespace.update(
                {"__class_getitem__": Connection._partial_spec_mfld_pass_to_base}
            )

        return PartialSpec(
            f"Connection[{bundle.__name__}]",
            (cls,),
            namespace,
            creating_derived=True,
        )

    def _partial_spec_mfld_pass_to_base(cls, args):
        underlying_base: type[Manifold] = args
        upd_bundle = cls._bundle[underlying_base]

        n = upd_bundle.base.dim
        r = upd_bundle.rank
        coeffs_shape = (r, r, n)

        return PartialSpec(
            f"Connection[{upd_bundle.__name__}]",
            (cls,),
            {"_bundle": upd_bundle, "_coeffs_shape": coeffs_shape},
            creating_derived=True,
            top_level_type=cls._top_level_type,
        )

    def __init__(self):
        if type(self) == Connection:
            raise TypeError(
                "connectinos cannot be instantiated without being subclassed"
            )
        self._cfg = ConnectionMethodConfig()  # defaults

    @classproperty
    def bundle(cls):
        return cls._bundle

    @property
    def cfg(self):
        return self._cfg

    def coeffs(self, p: Union[Point[Self._bundle.base], torch.Tensor]) -> torch.Tensor:
        p = Point[self._bundle.base](p)  # ensures that the point is compatible
        coeffs = self.eval(p)
        if coeffs.shape != self._coeffs_shape:
            raise ValueError(
                f"connection coefficients generated by {self.__class__.__name__} is incorrect shape"
            )
        return coeffs

    def partials(
        self, p: Union[Point[Self._bundle.base], torch.Tensor]
    ) -> torch.Tensor:
        p = Point[self._bundle.base](p)
        partials = self.eval_partials(p.p)

        n = self._bundle.base.dim
        r = self._bundle.rank
        expected_shape = torch.Size([r, r, n, n])

        print(f"partials shape: {partials.shape}")
        print(f"expected shape: {expected_shape}")

        if partials.shape != expected_shape:
            raise ValueError(
                f"partials generated by {self.__class__.__name__} is unexpected shape"
            )

        return partials

    @abstractmethod
    def eval(self, p: torch.Tensor) -> torch.Tensor:
        # NOTE: default behavior assumes that the eval mapping is continuous, must override if discrete or approximate
        pass

    @abstractmethod
    def eval_partials(self, p: torch.Tensor) -> torch.Tensor:
        # NOTE: default behavior assumes that the eval mapping is continuous, must override if discrete or approximate
        print(f"p: {p}")

        partials = jacrev(lambda q: self.eval(q))(p)
        return partials

    # TODO: maybe come up with better methods that come up with intermediary results

    def exp(
        p: Union[Point[Self._bundle.base], torch.Tensor],
        v: Vec[Self._bundle.base],
        method: Optional[ExpMapMethod] = None,
    ) -> Tuple[Point[Self._bundle.base], BundleCurve[Self._bundle.base]]:
        # TODO: call the method in each handler
        pass

    def log(
        p: Union[Point[Self._bundle.base], torch.Tensor],
        q: Union[Point[Self._bundle.base], torch.Tensor],
        method: Optional[LogMapMethod] = None,
    ) -> Tuple[Vec[Self._bundle.base], BundleCurve[Self._bundle.base]]:
        # TODO: call the method in each handler
        pass

    def parallel_transport_vec(
        v: Vec[Self._bundle.base],
        curve: BundleCurve[Self._bundle.base],
        method: Optional[ParallelTranspVecMethod] = None,
    ) -> Vec[Self._bundle]:
        # TODO: call the method in each handler
        pass

    # # TODO: in the later Rust library ensure that the output type is determined based on FieldCovarDeriv

    # def covar(field:  Field[Tensor[Self._bundle]] & FieldCovarDeriv, vf: VectorField) -> Field:
    #     return field.covar(self, vf)

    # def total_covar(field: FieldCovarDeriv) -> Field:
    #     pass


#  method(p, v, conn)

# conn.exp_map(p, v, method)  # this makes more sense
